### PR TITLE
Add the excessive_create_list cop

### PR DESCRIPTION
**Pull request by ddieulivol**
Cop used to signal when we create a lot of factory objects with FactoryBot (configurable with the `MaxAmount` option).

```ruby
        # @example MaxAmount: 10 (default)
        #   # We do not allow more than 10 items to be created
        #
        #   # bad
        #   create_list(:merge_request, 1000, state: :opened)
        #
        #   # good
        #   create_list(:merge_request, 10, state: :opened)
        #
```

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

- [x] Added the new cop to `config/default.yml`.
- [x] The cop is configured as `Enabled: pending` in `config/default.yml`.
- [x] The cop documents examples of good and bad code.
- [x] The tests assert both that bad code is reported and that good code is not reported.
- [x] Set `VersionAdded: "<<next>>"` in `default/config.yml`.

If you have modified an existing cop's configuration options:

- [ ] Set `VersionChanged: "<<next>>"` in `config/default.yml`.

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Thank you!

**Comment by ydah** [comment]
CI seems to be failing, can you confirm?
https://github.com/rubocop/rubocop-factory_bot/actions/runs/6827313104/job/18570505855#step:5:1

**Comment by ydah** [comment]
If this is an offense, isn't there a way to resolve it? Because, for example, if you want to create a record beyond 10, you're creating it because that's what you need, right? But if they make it a violation, the only way to solve the problem is to disable this cop, and I don't think that will lead to a fundamental solution. If I have missed something, please point it out.

**Comment by pirj** [comment]
We can think of this as LineLength, NestedGroups or MultipleMemoizedHelpers. There is usually no easy or automated way to fix the latter two. However, usually letting those numbers slide is causing increased maintenance costs.
Even the default 10 seems excessive to me. One commonly used case that comes to mind that would need that many is pagination. But usually this can be tested with a lower `per_page` value, or even by stubbing a hardcoded per page const.

**Comment by ddieulivol** [comment]
> CI seems to be failing, can you confirm? https://github.com/rubocop/rubocop-factory_bot/actions/runs/6827313104/job/18570505855#step:5:1

It's probably a change introduced in the latest rubocop version (given that the `edge` Rubocop job is failing). I'll go ahead and make the change 👍.

**Comment by ddieulivol** [comment]
> > CI seems to be failing, can you confirm? https://github.com/rubocop/rubocop-factory_bot/actions/runs/6827313104/job/18570505855#step:5:1
> 
> It's probably a change introduced in the latest rubocop version (given that the `edge` Rubocop job is failing). I'll go ahead and make the change 👍.

Fixed in https://github.com/rubocop/rubocop-factory_bot/pull/83/commits/ad516875df4d19f7f9d857dd3e5ea12ed0aeef33.

**Comment by pirj** [comment]
@ydah please merge at will

**Comment by ydah** [comment]
@ddieulivol Thank you for your great work!

**Comment by ddieulivol** [comment]
Quick question: What's the release cadence for this gem? Is there a number of new features to be reached before we release a new version?

**Comment by ydah** [comment]
The following PRs will be merged:
- https://github.com/rubocop/rubocop-factory_bot/pull/86

And, we would like to proceed to release once the following issues are resolved:
https://github.com/rubocop/rubocop-factory_bot/issues/80

**Pull request merged**
