### PR TITLE
Change `FactoryBot/CreateList` so that it checks same factory calls in an Array

### PR DESCRIPTION
**Pull request by r7kamura**
Recreated from the following pull request:

- https://github.com/rubocop/rubocop-rspec/pull/1467

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by ydah — APPROVED** [review]
Looks good! Thank you!

**Comment by ydah** [comment]
@r7kamura Could you resolved conflicts?

**Comment by pirj** [comment]
@r7kamura I've made an adjustment to use `.map` to follow #29. Please confirm that everything is in order.
I intend to merge, we can adjust later on.

**Comment by pirj** [comment]
Thank you, @r7kamura !

**Pull request merged**
