### PR TITLE
Add job for CI using Prism parser

### PR DESCRIPTION
**Pull request by ydah**
Follow up rubocop/rubocop-ast#277

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
Same as https://github.com/rubocop/rubocop-capybara/pull/112/files#r1533586083

interestingly, the job fails.

**Review by pirj — APPROVED** [review]
Thanks!

**Comment by pirj** [comment]
Should we update rubocop-ast? Or will the latest used anyway in the build? Or will this use the latest cached?
Should we report the error to prism?

**Comment by ydah** [comment]
I think rubocop-ast is up to date. This is a [prism](https://github.com/ruby/prism) issue and will be resolved by the next version of prism.

**Pull request merged**
