### PR TITLE
Bump version v2.25.0

### PR DESCRIPTION
**Pull request by ydah**
TODO:
- [x] https://github.com/rubocop/rubocop-factory_bot/pull/86
- [x] Execute cut_release again after merging the above PR

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Review by Darhazer — APPROVED** [review]

**Comment by ydah** [comment]
@pirj Sorry to bother you, but how about https://github.com/rubocop/rubocop-factory_bot/pull/86 ?

**Comment by pirj** [comment]
@ydah let’s include it! 👍

**Comment by pirj** [comment]
Release at will

**Comment by ydah** [comment]
Thank you!! I updated this PR.

**Pull request merged**
